from django.urls import path, include
from .views import (
    CreateUserView,
    CurrentUserView,
    PublicUserView,
    CookieTokenRefreshView,
    LogoutView,
    EmailTokenObtainPairView,
    VerifyEmailView,
    ResendVerificationEmailView,
    SportListView,
    CourtCenterDraftCreateView,
    CourtCenterCustomerDetailView,
    CourtCenterCustomerListView,
    CourtCenterCustomerTimeslotsView,
    MyCourtCenterListView,
    ImageUploadView,
    MyCourtCenterDetailsView,
    MyCourtCenterSchedulesView,
    MyCourtCenterPublishView,
    ProfileView,
    SpeculateLineItemListViewForCustomer,
    ConfirmPaymentView,
    InitiateTransactionView,
    TransactionDetailView,
    MyCourtCenterArchiveView,
    MyTransactionListView,
    RequestReviewView,
    MyTransactionCountsView,
    SendMessageView,
    ConversationReadView,
    ReadMessageListAPIView,
    DirectConversationView,
    ConversationSeenView,
)



urlpatterns = [
    path('register', CreateUserView.as_view(), name='register'),
    path('me', CurrentUserView.as_view(), name='current_user'),
    path('users/<int:pk>', PublicUserView.as_view(), name='public_user'),
    path('token', EmailTokenObtainPairView.as_view(), name='get_token'),
    path('token/refresh', CookieTokenRefreshView.as_view(), name='refresh_token'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('verify-email', VerifyEmailView.as_view(), name='verify_email'),
    path('api-auth', include('rest_framework.urls')),
    path('resend-verification-email', ResendVerificationEmailView.as_view(), name='resend_verification_email'),
    path('sports', SportListView.as_view(), name='sport_list'),
    path('images/upload', ImageUploadView.as_view(), name='image_upload'),
    # court center
    path('court-centers', CourtCenterCustomerListView.as_view(), name='court_center_customer_list'),
    path('court-centers/<int:pk>', CourtCenterCustomerDetailView.as_view(), name='court_center_customer_detail'),
    path('court-centers/<int:pk>/timeslots', CourtCenterCustomerTimeslotsView.as_view(), name='court_center_customer_timeslots'),
    path('court-centers/mine', MyCourtCenterListView.as_view(), name='court_center_owner_list'),
    path('court-centers/create-draft', CourtCenterDraftCreateView.as_view(), name='court_center_create_draft'),
    path('court-centers/mine/<int:pk>', MyCourtCenterDetailsView.as_view(), name='court_center_detail'),
    path('court-centers/mine/<int:pk>/schedules', MyCourtCenterSchedulesView.as_view(), name='court_center_schedules'),
    path('court-centers/mine/<int:pk>/publish', MyCourtCenterPublishView.as_view(), name='court_center_publish'),
    path('court-centers/mine/<int:pk>/archive', MyCourtCenterArchiveView.as_view(), name='court_center_archive'),
    #profile
    path('profile', ProfileView.as_view(), name='profile'),

    #transaction for customer
    path('line-items/customer', SpeculateLineItemListViewForCustomer.as_view(), name='speculate_line_item_list_for_customer'),
    path('transactions/initiate', InitiateTransactionView.as_view(), name='initiate_transaction'),
    path('transactions/<int:pk>', TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/<int:pk>/confirm-payment', ConfirmPaymentView.as_view(), name='confirm_payment'),
    path('transactions/<int:pk>/request-review', RequestReviewView.as_view(), name='request_review'),

    path('transactions/mine', MyTransactionListView.as_view(), name='my_transaction_list'),
    path("transactions/mine/counts", MyTransactionCountsView.as_view(), name='my_transaction_overview'),

    #conversation
    path('messages/send', SendMessageView.as_view(), name='send_message'),
    path('messages/<int:conversation_id>', ReadMessageListAPIView.as_view(), name='read_message_list'),
    path('conversations', ConversationReadView.as_view(), name='conversation_read'),
    path('conversations/dm', DirectConversationView.as_view(), name='dm_conversation'),
    path('conversations/<int:conversation_id>/seen', ConversationSeenView.as_view(), name='conversation_seen'),
]
