# Generated by Django 6.0.6 on 2026-06-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_seed_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcenter',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
