# Generated by Django 6.0.6 on 2026-06-09 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_courtcenter_status'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_logo_per_object',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='api_image_owner_i_74344c_idx',
            old_name='api_image_owner_c_6d8f1a_idx',
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'logo'), ('content_type__isnull', False)), fields=('content_type', 'object_id'), name='unique_logo_per_object'),
        ),
    ]
