# Generated by Django 6.0.6 on 2026-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
