# Generated by Django 6.0.6 on 2026-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_court_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price_currency',
            field=models.CharField(default='VND', max_length=3),
        ),
    ]
