# Generated by Django 6.0.6 on 2026-06-16 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_court_price_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_state', models.IntegerField(choices=[(0, 'Initial'), (1, 'Pending payment'), (2, 'Payment expired'), (3, 'Confirmed'), (4, 'Completed'), (5, 'Cancelled')], default=0)),
                ('process_name', models.CharField(default='court-booking', max_length=64)),
                ('line_items', models.JSONField(default=list)),
                ('last_transition_at', models.DateTimeField(auto_now_add=True)),
                ('last_transition', models.CharField(blank=True, choices=[('initiate', 'Initiate'), ('confirm_payment', 'Confirm payment'), ('cancel_payment', 'Cancel payment'), ('cancel', 'Cancel'), ('expire_payment', 'Expire payment'), ('complete', 'Complete')], max_length=32)),
                ('pay_in_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_in_total_currency', models.CharField(max_length=3)),
                ('pay_out_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_out_total_currency', models.CharField(max_length=3)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.court')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.transaction'),
        ),
    ]
