# Generated by Django 6.0.6 on 2026-06-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_court_slot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courtslot',
            new_name='api_courtsl_court_i_5fa66b_idx',
            old_name='api_courtsl_court_i_date_is_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='courtslot',
            new_name='api_courtsl_date_da6816_idx',
            old_name='api_courtsl_date_is_avail_idx',
        ),
    ]
