# Generated by Django 6.0.6 on 2026-06-17 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_api_courtsl_court_i_date_is_avail_idx_api_courtsl_court_i_5fa66b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='courtcenter',
            name='review_average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='courtcenter',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courtcenter',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('archived', 'Archived'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['center_id', 'sport_id', '-created_at'], name='api_court_center__9831e1_idx'),
        ),
        migrations.AddIndex(
            model_name='courtcenter',
            index=models.Index(fields=['status', '-created_at'], name='api_courtce_status_b34531_idx'),
        ),
        migrations.AddIndex(
            model_name='courtcenter',
            index=models.Index(fields=['status', 'latitude', 'longitude'], name='api_courtce_status_c718b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer_id', 'provider_id', 'court_id', '-created_at', 'current_state'], name='api_transac_custome_52e50d_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.transaction'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'transaction'), name='unique_review_per_transaction'),
        ),
    ]
