# Generated by Django 6.0.6 on 2026-08-07 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_review_courtcenter_review_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dm', 'DM'), ('muc', 'MUC')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_content', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_state',
            field=models.IntegerField(choices=[(0, 'Initial'), (1, 'Pending payment'), (2, 'Payment expired'), (3, 'Confirmed'), (4, 'Completed'), (5, 'Cancelled'), (6, 'Reviewed')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_transition',
            field=models.CharField(blank=True, choices=[('initiate', 'Initiate'), ('confirm_payment', 'Confirm payment'), ('cancel_payment', 'Cancel payment'), ('cancel', 'Cancel'), ('expire_payment', 'Expire payment'), ('complete', 'Complete'), ('review', 'Review')], max_length=32),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unread', models.IntegerField(default=0)),
                ('mention_unread', models.IntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_sender', to='api.member'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('sent', 'SENT'), ('acked', 'ACKED'), ('failed', 'FAILED')], default='pending', max_length=255)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['user'], name='api_member_user_id_d4cf67_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['conversation'], name='api_member_convers_297a20_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation'], name='api_message_convers_4567f6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['client_id'], name='api_message_client__b80ae6_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('client_id',), name='unique_conversation_client_id'),
        ),
    ]
