# Generated by Django 6.1.1 on 2026-09-08 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_review_courtcenter_review_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courts', to='api.sport'),
        ),
    ]
