# Generated by Django 6.0.6 on 2026-08-26 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_conversation_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.message'),
        ),
    ]
