# Generated by Django 6.0.6 on 2026-08-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_member_last_read_at_member_last_read_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_read_message_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
