# Generated by Django 6.0.6 on 2026-09-18 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_member_last_read_message_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_convers_4567f6_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation_id', '-id'], name='api_message_convers_fa3024_idx'),
        ),
    ]
