# Generated by Django 6.0.6 on 2026-09-21 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_message_api_message_convers_fa3024_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_convers_4567f6_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-id'], name='api_message_convers_fa3024_idx'),
        ),
    ]
