# Generated by Django 6.0.6 on 2026-09-21 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_message_api_message_convers_4567f6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_conversation_client_id',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='api_member_user_id_d4cf67_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='api_member_convers_297a20_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='api_message_client__b80ae6_idx',
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='unique_user_conversation'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'client_id'), name='unique_conversation_client_id'),
        ),
    ]
