# Generated by Django 6.0.6 on 2026-09-22 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_message_unique_conversation_client_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='court',
            name='api_court_center__9831e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='courtcenter',
            name='api_courtce_status_c718b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='courtslot',
            name='api_courtsl_date_da6816_idx',
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['center', 'sport'], name='api_court_center__b79472_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['sport', 'center'], name='api_court_sport_i_0e372f_idx'),
        ),
        migrations.AddIndex(
            model_name='courtcenter',
            index=models.Index(fields=['status', 'latitude'], name='api_courtce_status_d22554_idx'),
        ),
        migrations.AddIndex(
            model_name='courtslot',
            index=models.Index(condition=models.Q(('is_available', True)), fields=['date', 'start_time'], name='available_slots_by_date'),
        ),
    ]
