# Generated by Django 6.0.6 on 2026-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_courtcenter_status_latitude_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courtslot',
            name='available_slots_by_date',
        ),
        migrations.AddIndex(
            model_name='courtslot',
            index=models.Index(condition=models.Q(('is_available', True)), fields=['date', 'start_time'], include=('court',), name='available_slots_by_date'),
        ),
    ]
